### ISSUE TITLE
Enable user to create new requests

### ISSUE THREAD

**Issue by duckduckcodes** [duckduckcodes/devsensei#10]
We need to implement a way for the user to create new requests in the UI, such as a form or button. This may require updating the state to store new

**Comment by aao056** [comment]
@duckduckcodes have you worked on this so far?

**Comment by duckduckcodes** [comment]
no i haven't, you can work on it if you want to

**Comment by aao056** [comment]
@duckduckcodes I created a PR for that

**Comment by duckduckcodes** [comment]
i merged it, you made a new page for addrequest which is nice, but i think instead of that, later we can create a modal, so when user wants to create a new request, there's a modal that will open up,
other than that, things look good,
good job :100:

**Comment by aao056** [comment]
Yup, a modal is definitely a nicer idea and I firstly tried to do a pop up with the form, but I could not find a way to do it ( this is the first time I am touching Electron). I tried to get some information from their docs about pop-ups, but had no luck. 

If you could hand me some hints/resources on that, I am willing to change the approach and use a modal instead of a new page.

**Comment by duckduckcodes** [comment]
@aao056 actually you can implement a modal like you would do in a normal react app, i don't think it's framework specific,
here is a youtube video on how to do so: https://www.youtube.com/watch?v=ZCvemsUfwPQ
