### ISSUE TITLE
Implement responsive design for our API testing app

### ISSUE THREAD

**Issue by duckduckcodes** [duckduckcodes/devsensei#4]
The app would benefit from a responsive design that adjusts to different screen sizes and devices. We propose implementing a responsive design that ensures the app looks and works well on all desktop computers,

**Comment by aao056** [comment]
Do you plan to use some CSS framework like Tailwind?

**Comment by duckduckcodes** [comment]
for now we use css, but we will migrate to scss later (checkout #19)

**Comment by duckduckcodes** [comment]
@aao056 btw, i added some basic styling to the modal
![image](https://user-images.githubusercontent.com/123452104/229645370-f71b3d28-2fc9-4986-a64d-7e331e20ba8e.png)

**Comment by aao056** [comment]
should have asked you before starting to work on that by myself

**Comment by duckduckcodes** [comment]
yeah i also should've been more organized, but your code is throwing an error :'Cannot get index.html', which is weird since you only changed components, i'll look into it tomorrow

**Comment by aao056** [comment]
@duckduckcodes i have looked on it and its coming from /src/renderer/components/View/Request/AddRequest.tsx. i was working on the file on the same time with you and messed up. 

after adding div closing tags, the error is going away. it should be a quick fix , i can do it, but let me know if you are now working on this so that we do not make the same thing again
